apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/davidvicente95/docker-k8s-101/api 
    newTag: "latest"
  - name: ghcr.io/davidvicente95/docker-k8s-101/etl 
    newTag: "latest"

labels:
  - includeSelectors: true
    pairs:
      env: local